### ISSUE TITLE
Missing href API for sub entities (embedded link type) in EntityBuilder

### ISSUE THREAD

**Issue by kgston** [sdaschner/siren4javaee#1]
Assuming from your API, the EntityBuilder is both used for root and sub entities. For sub entities, we should be able to add a href property for [embedded link type sub entities](https://github.com/kevinswiber/siren#embedded-link). 

Any chance for this to be added?

**Comment by sdaschner** [comment]
Yes, for sake of simplicity there's only one type for both.

Oh, of course you're right. Now I'm wondering how I could have missed that... ;-)

Fixed in 557323d27f887b110b600f5d3f2f15eab0d0e386. Thanks!

**Comment by sdaschner** [comment]
... and available as `1.1` version.

**Comment by kgston** [comment]
Thanks for the quick response, and the great presentation at Java Day Tokyo :)
